from . import student_info
from . import standard_info
from . import teacher_info
from . import sports_activity
from . import library_info
from . import cultural_fest
from . import scholarship_info
from . import new
from . import sale_order
from . import product_template1
from . import weather1_info
from . import sale_comp
from . import account_vendor
